<a href="https://colab.research.google.com/github/ganeshingle9552/118/blob/main/gg1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating NumPy Arrays
From a Python List

In [10]:
import numpy as np
my_list = [1,2,3]
my_list
np.array(my_list)
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Built-in Methods

In [11]:
np.arange(0,10)
np.arange(0,11,2)
np.zeros(3)
np.zeros((5,5))
np.ones(3)
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

linspace

In [12]:
np.linspace(0,10,3)
np.linspace(0,10,50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

eye

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random

In [14]:
np.random.rand(2)
np.random.rand(5,5)

array([[0.60808419, 0.29957827, 0.91230591, 0.54760649, 0.56872114],
       [0.16528175, 0.66987885, 0.60792452, 0.63258704, 0.6704169 ],
       [0.83697824, 0.52820767, 0.13821587, 0.5387186 , 0.71255501],
       [0.50417127, 0.59896526, 0.95012694, 0.69824658, 0.19259035],
       [0.71490619, 0.03198313, 0.20697705, 0.19138603, 0.38341169]])

randn

In [15]:

np.random.randn(2)
np.random.randn(5,5)

array([[-0.24166456, -0.03337194,  0.26771746, -0.88703423,  0.20387979],
       [ 0.46094951, -1.3529995 ,  1.20032748, -0.03989569, -1.02115103],
       [-1.36430601, -1.72815525,  1.25614984, -0.12054416, -1.28135094],
       [ 1.71891075,  0.59853438,  0.43768536,  1.55984511,  1.11230954],
       [-0.1315451 ,  1.56844197,  0.03217002,  0.89030272,  0.5266713 ]])

randint

In [16]:
np.random.randint(1,100)
np.random.randint(1,100,10)

array([28, 32, 84, 66, 73, 36, 23, 36, 55, 20])

Array Attributes and Methods

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
arr
ranarr

array([46,  1, 17, 15, 44, 14, 35, 20, 44, 33])

Reshape

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max,min,argmax,argmin

In [24]:
ranarr
ranarr.max()
ranarr.argmax()
ranarr.min()
ranarr.argmin()


np.int64(1)

Shape

In [25]:
arr.shape
arr.reshape(1,25)

arr.reshape(1,25).shape
arr.reshape(25,1)
arr.reshape(25,1).shape

(25, 1)

dtype

In [26]:
arr.dtype

dtype('int64')